### ISSUE TITLE
mvi question

### ISSUE THREAD

**Issue by soredake** [haasn/gentoo-conf#3]
Is there any way to scale only images that do not fit current windows size (size of image bigger that window size), for example in tiling?
or have  'video-unscaled no' option enabled only for images that do not fit window size and 'video-unscaled no' for images that fully fit the window (size of image smaller or equally than window size)

video-unscaled yes https://a.pomf.cat/lqftrm.png
video-unscaled no https://a.pomf.cat/uxiyar.png

same function exist in atom and called 'zoom to fit'
no zoom to fit https://a.pomf.cat/nkysyc.png
yes zoom to fit https://a.pomf.cat/gwctbq.png

example resize code from atom image-view package
https://github.com/atom/image-view/blob/master/styles/image-view.less#L90-L109

**Comment by haasn** [comment]
You could probably approximate it by trying to see if the image size is greater than the scaled image size / window size (somehow?), and then turn on `video-unscaled no` only in that case.

Apart from that, not sure if there's an easy way.
