### ISSUE TITLE
How to use the script!

### ISSUE THREAD

**Issue by Saed80** [haasn/gentoo-conf#5]
Hey!

I'm an absolute beginner regarding MPV and using scripts. I'v searched google and youtube for hours and couldn't figure out how to use the script.  I tried using MPV with gui and still couldn't figure out how to use any script. 
 I wish you can guide to how to use this script :)

Thanks.

**Comment by haasn** [comment]
I don't even understand what "script" you're referring to.

**Comment by Saed80** [comment]
oh sorry I thought I submitted the issue on the same page. 

What I'm referring to is this

https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/shaders/noise.glsl

**Comment by haasn** [comment]
See the `--glsl-shader` option from the mpv documentation. (Example: `mpv FILE --glsl-shader=noise.glsl`)
